set Nginx_Dir=G:\nginx-1.16.1
REM set Nginx_Dir=F:\website\nginx-1.16.1
set Server_Dir=..\server
@REM set Server_Main=.\app.js
set Server_Main=.\pm2.json
set Stat_File_Dir=%Server_Dir%\modules
@REM set Stat_File_Name=files_stats_*.json
set Stat_File_Name=infos
set Scripts_Dir=%Server_Dir%\modules
set Script_Clear_Posters=.\clear-posters.js